apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.deployment.name }}"
  labels: "{{- include "labels" . | nindent 4 -}}"
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.deployment.image.app }}:{{ .Values.deployment.image.version }}"
          imagePullPolicy: "{{ .Values.deployment.image.pullPolicy }}"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
        {{- if eq .Values.container.enabled true -}}
        {{- include "container" . | nindent 8 -}}
        {{- end -}}