apiVersion: apps/v1
kind: Deployment
metadata:
  name: My-app-deploy
  labels:
    tier: front
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 4

  template:
    metadata:
      
        
  