apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana-deployment
  namespace: kube-system
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:6.6.1
          env:
            - name: ELASTICSEARCH_HOSTS
              value: "elasticsearch:9200"
          ports:
            - containerPort: 5601
              name: webinterface
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: kube-system
  labels:
    service: kibana
spec:
  type: NodePort
  ports:
    - port: 5601
      name: webinterface
  selector:
    app: kibana